<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Configuration</name>
   <tag></tag>
   <elementGuidId>2a181225-bdff-4df4-9b7a-74dc00e6758a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_pim_Configuration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pim_Configuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>beb0329d-b6d8-4c6e-9a0b-5a7815b17665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>db61db8e-e654-4662-8c8f-bff658cb188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pim_Configuration</value>
      <webElementGuid>afe96fbc-6a11-4275-a875-71caf2a769b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>20328a43-f56b-45d1-90af-fa8c12506cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configuration</value>
      <webElementGuid>b724e9d1-e5bc-474b-a39f-33aefb5f35e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pim_Configuration&quot;)</value>
      <webElementGuid>5c703e12-6b8c-4d1e-b931-9f193376f866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pim_Configuration']</value>
      <webElementGuid>d19b5cb5-3a0d-401b-a518-715ca3775b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[2]/ul/li/a</value>
      <webElementGuid>f36c42e8-02da-45e3-aad3-0211d75d994b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Configuration')])[3]</value>
      <webElementGuid>8017885b-dd39-4643-95fa-c25a12d206fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIM'])[1]/following::a[1]</value>
      <webElementGuid>445c4d90-d717-469b-a14f-7dc0a66376ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register OAuth Client'])[1]/following::a[2]</value>
      <webElementGuid>cfac1b94-b344-45b3-be9a-2330ad6c3ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional Fields'])[1]/preceding::a[1]</value>
      <webElementGuid>2edf62dd-37c3-4bc8-9968-68678c7f248a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Fields'])[1]/preceding::a[2]</value>
      <webElementGuid>3e521a4f-57e3-478e-bde4-987f9c53a060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>e511a2e3-7000-4083-9efd-16d2e8f3b595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>b9a0e523-31f3-4458-9e96-281a8eec1a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'menu_pim_Configuration' and (text() = 'Configuration' or . = 'Configuration')]</value>
      <webElementGuid>c60a13c1-ab66-4379-8a65-6c8f3764785d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
