<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Corporate Branding</name>
   <tag></tag>
   <elementGuidId>addb4a05-71c4-4446-9d4b-06e9fc7271ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_admin_addTheme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_admin_addTheme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3aeac25-c638-4ea4-a949-5c8ed7eea8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/admin/addTheme</value>
      <webElementGuid>a2068428-8b13-4955-ab72-ca9ad8498146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_admin_addTheme</value>
      <webElementGuid>3e079e32-95e1-473c-a5c6-435321888a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate Branding</value>
      <webElementGuid>96de9446-59a9-4781-90a6-b11eab1e72ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_admin_addTheme&quot;)</value>
      <webElementGuid>96385988-0b28-459f-99c2-d54f13773db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_admin_addTheme']</value>
      <webElementGuid>e09e0b2d-f542-4dc9-9ca8-c7281b854918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li/ul/li[6]/a</value>
      <webElementGuid>4c3977b2-93c5-4059-b82b-683bdf8470bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Corporate Branding')]</value>
      <webElementGuid>3d013edd-6807-4bdb-8146-c0948c4a3299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationalities'])[1]/following::a[1]</value>
      <webElementGuid>06301957-97a1-4a29-8fb8-2861cfda3b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memberships'])[1]/following::a[2]</value>
      <webElementGuid>c70bff36-21ab-40d7-9c26-c40e62ef7126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Configuration'])[1]/preceding::a[2]</value>
      <webElementGuid>cdf4e39e-8832-4c21-a70e-c5465125a805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Subscriptions'])[1]/preceding::a[3]</value>
      <webElementGuid>814e6b04-7b78-4633-ba40-228de87bd5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate Branding']/parent::*</value>
      <webElementGuid>e8ec7ebe-8664-4690-a20a-be11b7e5a2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/admin/addTheme')]</value>
      <webElementGuid>8c2bc17d-300d-4353-8169-067523145d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[6]/a</value>
      <webElementGuid>7323f70b-e3f1-4263-a4d7-9d2e77b4ed39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/admin/addTheme' and @id = 'menu_admin_addTheme' and (text() = 'Corporate Branding' or . = 'Corporate Branding')]</value>
      <webElementGuid>6acc126f-9d8f-4f2e-a7df-06a21fefc44f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
