<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>9ff209b9-a97f-41e3-a6b2-4b1c28b4dcb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_core_viewDefinedPredefinedReports</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2413e58c-41f9-40ef-a2f5-1bf4c81f1162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED</value>
      <webElementGuid>318173e6-9b68-4c31-90b8-87afb3154b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_core_viewDefinedPredefinedReports</value>
      <webElementGuid>b5e90c0c-e3be-4093-91df-0876b76eeee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>835d5a9a-6510-4e49-a4ae-69c8865ff38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_core_viewDefinedPredefinedReports&quot;)</value>
      <webElementGuid>ac094612-37f1-4328-9e2d-13b51257374d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      <webElementGuid>e55ec427-2fd8-4783-beed-16b866c17e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[2]/ul/li[4]/a</value>
      <webElementGuid>0b16b548-71b5-4273-8508-ea8dd8f013cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reports')]</value>
      <webElementGuid>90c07df1-f977-4df9-81c1-86f545405323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Employee'])[1]/following::a[1]</value>
      <webElementGuid>d33479cb-617f-47a8-92ac-d53d129e3e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/following::a[2]</value>
      <webElementGuid>dd3ff018-ff6e-4fc5-9fca-af24c6a2db77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>2d110e34-f4c9-404a-801f-8ef2b228be89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::a[2]</value>
      <webElementGuid>24dbb49b-acb6-4e87-a7d5-ac752e578b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reports']/parent::*</value>
      <webElementGuid>96571d08-616a-414e-ba4a-c4c016efce3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED')]</value>
      <webElementGuid>4dc4cc36-db47-4882-bdef-4ff194556434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>4271ea3f-9102-49b4-ae0c-92e29eb2352e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED' and @id = 'menu_core_viewDefinedPredefinedReports' and (text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>25224892-620e-4ac3-9e01-d7d1f75e834b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
