<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Username</name>
   <tag></tag>
   <elementGuidId>d671fb75-cc1a-4803-9ab4-91ba8e0d6dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.null</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/thead/tr/th[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>507980d3-b8d3-419c-b75d-64c652e4113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://opensource-demo.orangehrmlive.com/index.php/admin/viewSystemUsers?sortField=user_name&amp;sortOrder=ASC</value>
      <webElementGuid>8d7ec962-25cb-4438-8d84-733f9ca8895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>c390ba04-ec3f-4282-a44a-d25b9b56e826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/thead[1]/tr[1]/th[@class=&quot;header&quot;]/a[@class=&quot;null&quot;]</value>
      <webElementGuid>03a7b486-cbf0-49df-bb23-c2921a63ba6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/thead/tr/th[2]/a</value>
      <webElementGuid>3dacc8df-4990-4c10-9d52-ede80c68e606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Username')]</value>
      <webElementGuid>759bcb10-acf7-4552-abdc-cbe61ac7b6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last'])[1]/following::a[1]</value>
      <webElementGuid>415c39cf-1926-41aa-b3f4-47fa05298829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[2]</value>
      <webElementGuid>506a0cee-e53f-42ed-99de-86b74c749417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Role'])[2]/preceding::a[1]</value>
      <webElementGuid>0a5163ff-d2c8-48e8-b9e9-84ec43d5475d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[2]/preceding::a[2]</value>
      <webElementGuid>a9af7662-e766-4d0e-b0c7-896575497aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://opensource-demo.orangehrmlive.com/index.php/admin/viewSystemUsers?sortField=user_name&amp;sortOrder=ASC')]</value>
      <webElementGuid>762ac502-7e85-4210-9925-bc9bb9c997d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/a</value>
      <webElementGuid>ea03ab5b-34fb-468c-b757-ca8e14d7cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://opensource-demo.orangehrmlive.com/index.php/admin/viewSystemUsers?sortField=user_name&amp;sortOrder=ASC' and (text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>3cabb138-d32f-4345-86cc-920c2833c105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
