<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM Username_securityAuthentica_26f883</name>
   <tag></tag>
   <elementGuidId>ba3acb88-6460-4a02-ba2c-dbd277b13a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#securityAuthentication_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAuthentication_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bf48bda-720c-4ff5-a6a5-30bfb56f834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bf87632-2c58-4a42-bc7d-9946fd5e6b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>securityAuthentication[userName]</value>
      <webElementGuid>11f65541-cce1-4273-b945-f22de992e1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAuthentication_userName</value>
      <webElementGuid>372996e8-66a6-46a6-acdb-1ff1d4e06864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAuthentication_userName&quot;)</value>
      <webElementGuid>5d7cbe1d-a3bb-42dc-9e8d-b501dfd681aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAuthentication_userName']</value>
      <webElementGuid>2ad44553-17ce-4d2a-bf56-079dd6b094c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPasswordForm']/fieldset/ol/li/input</value>
      <webElementGuid>872c83fe-432b-45e7-ab16-889ad4cdc0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>fe1620be-c63c-4b60-b0c1-c92c2fc6ca1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'securityAuthentication[userName]' and @id = 'securityAuthentication_userName']</value>
      <webElementGuid>340e1c9b-c162-4fcc-9071-ad5f416ee2ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
