<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_not_postSubmitBtn</name>
   <tag></tag>
   <elementGuidId>9638df8a-2704-4f11-bf69-25b0078e9bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postSubmitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postSubmitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f7812e8-dac9-43bc-acac-9d5082c643c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postSubmitBtn</value>
      <webElementGuid>b6e30851-7108-47fa-a8f4-c1c844ad2915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submitBtn hover</value>
      <webElementGuid>7933dda6-a3c1-4970-a119-19d3ef362f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4dc9662-970f-49be-86de-a37f0361f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>b2c19a9a-1d78-4349-92c7-e7a11fe4f6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postSubmitBtn&quot;)</value>
      <webElementGuid>97e5ffc6-3f52-497c-9abc-29169eb6eeb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postSubmitBtn']</value>
      <webElementGuid>44bf6f1e-2383-4af6-8e02-c1e7ea5e68cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page1']/p/input</value>
      <webElementGuid>7d180e6b-cc00-499c-8c1e-d12ef12a4997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>0776848e-a5cf-4273-9f52-6aa111b05cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postSubmitBtn' and @type = 'button']</value>
      <webElementGuid>dfe60aea-cb0e-4df2-91f7-aafa7cc24f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
