<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_personaloptGender</name>
   <tag></tag>
   <elementGuidId>c713c32b-c6a6-45f2-8f90-7451a4bc2cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_optGender_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_optGender_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f8e7d03-f814-44f0-accb-e2294e4c95e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[optGender]</value>
      <webElementGuid>feea5713-489d-4484-9b1a-3a21a6524d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>11b96bdc-ac6a-4601-8d17-0a16f1571de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad86aae4-9508-4dba-a239-f51107e6716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_optGender_1</value>
      <webElementGuid>51a425f5-8caf-42f9-8c9e-b62a42d328a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>aae94299-257c-4fdc-9b0c-b9750d6b1e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_optGender_1&quot;)</value>
      <webElementGuid>8bb0ac8e-30b6-46d0-9d58-3328aacbc9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_optGender_1']</value>
      <webElementGuid>845c434a-201d-4f15-aee7-5c02fc4df4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li/ul/li/input</value>
      <webElementGuid>fa0fe401-febe-4937-9592-cf968811660d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li/input</value>
      <webElementGuid>31416e3e-36cd-4da4-a03c-08c212a59081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'personal[optGender]' and @type = 'radio' and @id = 'personal_optGender_1']</value>
      <webElementGuid>acf642da-c9a2-4260-ba9d-f17f66ed8e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
