<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status__search</name>
   <tag></tag>
   <elementGuidId>2d3e9f56-cbad-4600-8bc0-a8a145bada70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc35088a-d985-4845-b85e-13f12d59ef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00c37778-daf1-4c7d-9ca9-c33c6dc703d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchbutton hover</value>
      <webElementGuid>a68bbcc0-a2d9-400f-b23b-fe168bcbae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBtn</value>
      <webElementGuid>d260bd28-7580-4f33-ad88-fcf40fd13b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>fe9b75ae-739d-4c4c-9c42-764439f05bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_search</value>
      <webElementGuid>90e5f86e-47a7-44a6-a7a8-e7ff2d5e777e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBtn&quot;)</value>
      <webElementGuid>4f1db157-0a74-420f-a373-865c8dc60eb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBtn']</value>
      <webElementGuid>d9ac1894-23db-4a5c-be26-58091575c7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/p/input</value>
      <webElementGuid>b4c38d88-0183-45bd-b09b-5830bd15a89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>41933d4e-37f1-40d5-9df4-c1fa4cbe95c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'searchBtn' and @name = '_search']</value>
      <webElementGuid>5aeb1240-94c2-404f-bf0a-e7dfd35078ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
