<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_personalDOB</name>
   <tag></tag>
   <elementGuidId>66af2874-ed19-4406-8c1c-061a9851dcb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal_DOB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_DOB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbb411e4-b836-4bad-895b-a9ab59c870f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_DOB</value>
      <webElementGuid>a40750b2-6b20-4940-86a9-691188144cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55951381-d0b1-4486-9756-3d9915ed20a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[DOB]</value>
      <webElementGuid>0744fc99-cce2-4bf3-8ec0-ef2b6b4600fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable calendar hasDatepicker</value>
      <webElementGuid>c3fd963a-6a40-4cb5-9b3c-653177d333e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_DOB&quot;)</value>
      <webElementGuid>7498ddda-772b-4f8e-a4b1-0577cbce7369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_DOB']</value>
      <webElementGuid>16d9387a-9d30-4157-899f-b88193808733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li[4]/input</value>
      <webElementGuid>4dc1ac7c-fdb3-458c-b3fe-2afa081134ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[4]/input</value>
      <webElementGuid>d54554b0-c69e-41f1-8533-454b3d605d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_DOB' and @type = 'text' and @name = 'personal[DOB]']</value>
      <webElementGuid>cc16e04f-96a4-40c0-89f5-16c02eecc06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
