<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Delete records</name>
   <tag></tag>
   <elementGuidId>190e55d3-088b-4098-b569-f959526208b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deleteConfModal > div.modal-body > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='deleteConfModal']/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>13521dd0-918a-464c-8c8e-6729b259a72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete records?</value>
      <webElementGuid>f079d4fa-101b-4a9c-ba30-d09e24419af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteConfModal&quot;)/div[@class=&quot;modal-body&quot;]/p[1]</value>
      <webElementGuid>9df33beb-7ed7-4fde-ba95-914699584cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfModal']/div[2]/p</value>
      <webElementGuid>459810a2-edfc-4b52-bcc1-ae987268c7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM - Confirmation Required'])[1]/following::p[1]</value>
      <webElementGuid>f9180b06-fbfc-47ed-a606-7f77d71e4be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::p[1]</value>
      <webElementGuid>234f9636-8513-45fd-aff2-a43841885360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM, Inc'])[1]/preceding::p[1]</value>
      <webElementGuid>c075c5d8-683f-44cc-926e-155fccb3dbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete records?']/parent::*</value>
      <webElementGuid>51b12c18-5170-4c32-a152-d53144863e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p</value>
      <webElementGuid>7f2c8899-a37f-4294-b6ea-4251dc8b1f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Delete records?' or . = 'Delete records?')]</value>
      <webElementGuid>fe08e470-e825-4718-8d63-ec5a5f62b2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
